### ISSUE TITLE
debian package build installs in /usr but signalwire_client2.pc contains /usr/local

### ISSUE THREAD

**Issue by motylewski** [signalwire/signalwire-c#129]
I have checked out signalwire-c master 1155e10
Linux Mint 21.3 MATE

`PACKAGE_RELEASE="50" cmake . -DCMAKE_BUILD_TYPE=Release && make package`

does create signalwire-client-c2_2.0.1-50_virginia_amd64.deb 
after installing it, header files are in /usr/include/signalwire-client-c2/signalwire-client-c/
But `pkg-config signalwire_client2 --cflags` gives:
-I/usr/**local**/include/signalwire-client-c2
which leads to freeswitch compile error.
```
mod_signalwire.c:28:10: fatal error: signalwire-client-c/client.h: No such file or directory
   28 | #include <signalwire-client-c/client.h>
```

/usr/lib/pkgconfig/signalwire_client2.pc contains **prefix=/usr/local**

I have no idea how to fix that /usr, /usr/local prefix mismatch.

**Comment by andywolk** [comment]
See how it's done here:
https://github.com/signalwire/signalwire-c/blob/master/.github/docker/debian/bookworm/amd64/Dockerfile#L91

**Comment by motylewski** [comment]
OK, I have tested
`PACKAGE_RELEASE="51" cmake . -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX="/usr" && make package`

and it has created correct signalwire_client2.pc with prefix=/usr
Please **update documentation**: https://github.com/signalwire/signalwire-c/blob/master/README :
Is:
`PACKAGE_RELEASE="42" cmake . -DCMAKE_BUILD_TYPE=Release && make package`
Should be:
`PACKAGE_RELEASE="42" cmake . -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX="/usr" && make package`
