### ISSUE TITLE
CMake Error at CMakeLists.txt:260 (string):

### ISSUE THREAD

**Issue by hpr504** [signalwire/signalwire-c#41]
Hi there, after git clone https://github.com/signalwire/signalwire-c.git, I entered sudo cmake ., there's a problem. The error log is as flows:
------------------------------------------------------------------------------------------------
shengdong252@shengdong252-virtual-machine:~/signalwire-c$ sudo cmake .
-- cotire 1.7.10 loaded.
SignalWire-Client-C 1.2
Found LibKS 1.3.0 package at path /usr/include/libks
Platform is linux
Build type: Debug CXX Flags: 
Install prefix: /usr/local
Platform is linux
Build type: Debug CXX Flags: 
Install prefix: /usr/local
CMake Error at CMakeLists.txt:260 (string):
  string sub-command REPLACE requires at least four arguments.

-- Configuring incomplete, errors occurred!
See also "/home/shengdong252/signalwire-c/CMakeFiles/CMakeOutput.log".
-----------------------------------------------------------------------------------------
The CMakeLists.txt:260 is :
option(CMAKE_USE_FOLDERS "Enable folder grouping of projects in IDEs." ON)

Can you tell me how to fix it?

**Comment by seven1240** [comment]
try this https://github.com/signalwire/libks/issues/42

**Comment by hpr504** [comment]
> try this [signalwire/libks#42](https://github.com/signalwire/libks/issues/42)

thanks, I've solved it~
